version: '3'
services:
  aichieve-mongodb:
    container_name: mongodb
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  aichieve-auth:
    build: auth/.
    container_name: auth
    ports:
      - "49001:13337"
  aichieve-idea:
    build: idea/.
    container_name: idea
    ports:
      - "49002:13337"
  aichieve-main:
    build: main/.
    container_name: main
    ports:
      - "49003:13337"
networks:
    default:
    internal:
        internal: true

