version: '2'
services:
  aichieve-mongodb:
    container_name: mongodb
    image: mongo
    volumes:
      - mongodata:/data/db
    expose:
      - "80"
  aichieve-auth:
    build: auth/.
    container_name: auth
    expose:
      - "80"
    depends_on:
      - aichieve-mongodb
  aichieve-idea:
    build: idea/.
    container_name: idea
    expose:
      - "80"
    depends_on:
      - aichieve-mongodb
  aichieve-main:
    build: main/.
    container_name: main
    ports:
      - "80:8080"
    depends_on:
      - aichieve-mongodb
  aichieve-frontend:
    build: frontend/.
    container_name: frontend
    expose:
      - "80"
    depends_on:
      - aichieve-mongodb

volumes:
  mongodata:
    external: false
    
# networks: 
#   default:
#     driver: bridge