version: '2'
services:
  aichieve-mongodb:
    container_name: mongodb
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:80"
  aichieve-auth:
    build: auth/.
    container_name: auth
    ports:
      - "49001:80"
    depends_on:
      - aichieve-mongodb
  aichieve-idea:
    build: idea/.
    container_name: idea
    ports:
      - "49002:80"
    depends_on:
      - aichieve-mongodb
  aichieve-main:
    build: main/.
    container_name: main
    ports:
      - "49003:80"
    depends_on:
      - aichieve-mongodb
  aichieve-frontend:
    build: frontend/.
    container_name: frontend
    ports:
      - "49004:80"
    depends_on:
      - aichieve-mongodb

networks: 
  default:
    driver: bridge