version: '2'
services:
  aichieve-mongodb:
    container_name: mongodb
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  aichieve-auth:
    build: auth/.
    container_name: auth
    ports:
      - "49001:13337"
    depends_on:
      - aichieve-mongodb
  aichieve-idea:
    build: idea/.
    container_name: idea
    ports:
      - "49002:13337"
    depends_on:
      - aichieve-mongodb
  aichieve-main:
    build: main/.
    container_name: main
    ports:
      - "49003:13337"
    depends_on:
      - aichieve-mongodb

networks: 
  default:
    driver: bridge